proj3: proj3.o Edge.o Vertex.o Graph.o Matrix.o
	g++ proj3.o Edge.o Vertex.o Graph.o Matrix.o -o proj3

proj3.o: proj3.cpp
	g++ -Wall -c proj3.cpp

Edge.o: Edge.cpp
	g++ -Wall -c Edge.cpp

Vertex.o: Vertex.cpp
	g++ -Wall -c Vertex.cpp

Matrix.o: Matrix.cpp
	g++ -Wall -c Matrix.cpp

Graph.o: Graph.cpp
	g++ -Wall -c Graph.cpp